### ISSUE TITLE
error: Element ref was specified as a string (wrapped) but no owner was set.

### ISSUE THREAD

**Issue by khaki4** [ckshekhar73/react-semantic-redux-form#3] opened 2017-10-05 14:35 UTC
If adding react-semantic-redux-form to existing node_modules, 
it is working well,
but if you remove the node_modules folder and re-install it,
the following error occurs

![screen shot 2017-10-05 at 11 28 10 pm](https://user-images.githubusercontent.com/8818375/31232718-9e1549fe-aa25-11e7-994c-a3b16d00067b.png)

this is my package.json
and I'm using create-react-app CLI
> {
  "name": "redux_form_practice",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "axios": "^0.16.2",
    "lodash": "^4.17.4",
    "react": "^16.0.0",
    "react-dom": "^16.0.0",
    "react-redux": "^5.0.6",
    "react-router-dom": "4.2.2",
    "react-scripts": "1.0.14",
    "react-semantic-redux-form": "^1.1.6",
    "redux": "^3.7.2",
    "redux-form": "^7.0.4",
    "redux-promise": "^0.5.3",
    "redux-thunk": "^2.2.0",
    "semantic-ui-react": "^0.74.2"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  },
  "devDependencies": {
    "@types/react": "^16.0.7",
    "babel-preset-react": "^6.24.1",
    "redux-devtools-extension": "^2.13.2"
  }
}

**Comment by ckshekhar** [comment] 2017-10-07 05:30
I have created one sample app with create-react-app CLI and followed as specified. But not able to reproduce error. Please check once more the bug in this package or other. I will try to add examples also.

**Comment by ckshekhar** [comment] 2017-10-08 14:54
I am closing this for now. If issue is not resolved please reopen it.

**Closed as completed by ckshekhar** 2017-10-08 14:54 UTC
